export enum ItemBoxViewMode {
  'MAXIMIZED' = 'MAXIMIZED',
  'MINIMIZED' = 'MINIMIZED',
}

export enum ItemBoxKind {
  EQUIPMENT = 'EQUIPMENT',
  CHARACTER = 'CHARACTER',
  MATERIAL = 'MATERIAL',
  TRAIN_EQUIPMENT = 'TRAIN_EQUIPMENT',
}
