export interface CharacterDetail {
  SKILLS: string[]
  RESONANCES: { [key: string]: string }
  AWAKENING: { [key: string]: string }
}

export const CHARACTER_DETAIL: {
  [key: string]: CharacterDetail | any
} = {
  RAZIEL_THE_REMINISCE: {},
  SHIRE: {},
  PELOTA: {},
  DOROTHY: {},
  JOSHUA: {},
  SOMMER: {},
  USHANA: {},
  SUMMERSHIZURU: {},
  NICOLA: {},
  DUSTIN: {},
  ANFIYA: {},
  HAYABUSA: {},
  JALHAY: {},
  ITHOS: {},
  IKUMA: {},
  LISSANDRA: {},
  MUMEI: {},
  PALADI: {},
  CONNOR: {},
  VERLAINE: {
    SKILLS: [
      '스타 아크',
      '드림 파인더',
      '드림 메이커',
      '공포의 밤',
      '진혼가',
      '마력샘',
      '별의 꿈',
      '드림 이터',
    ],
    RESONANCES: {
      1: '성맥',
      2: '몽유',
      3: '생기',
      4: '꿈의 여행자',
      5: '기원의 꿈',
    },
    AWAKENING: {
      1: '예지몽',
      2: '샘물',
      3: '투지',
      4: '잠꼬대',
      5: '단꿈',
    },
  },
  CHARLOTTE: {},
  SUEN: {},
  NAYUTA: {
    SKILLS: ['소실', '셔플', '미스터리', '해체의 번개', '재구축의 힘', '구축의 화염', '정화의 빛'],
    RESONANCES: {
      1: '독심술',
      2: '사기 마술',
      3: '생기',
      4: '감응',
      5: '레비스의 불가사의',
    },
    AWAKENING: {
      1: '강적',
      2: '아라야',
      3: '투지',
      4: '항하사',
      5: '무량',
    },
  },
  KATAS: {},
  WENSHENG: {},
  MARGIELA: {},
  ARINA: {},
  ILONA: {},
  STELLA: {},
  CAROLINE: {
    SKILLS: ['플라잉 플래시', '자석 폭탄', '번개 소용돌이'],
    RESONANCES: {
      1: '자석 감응',
      2: '고압',
      3: '생기',
      4: '감전',
      5: '전력 회수',
    },
    AWAKENING: {
      1: '추격',
      2: '격전',
      3: '투지',
      4: '뇌운 프로토콜',
      5: '무선 충전',
    },
  },
  TENNIE: {},
  HEINRICH: {},
  LIVIA: {},
  DESIREE: {},
  LIN: {},
  NABI: {},
  GANYA: {},
  YEJUE: {},
  AKIRA: {},
  ACHIWA: {},
  KALEYA: {},
  YER: {},
  FENIA: {},
  RINA_F: {},
  VALENTINE: {},
  YOIDUKI: {},
  AOBA: {},
  CECIL: {},
  MHAR: {},
  MSGOLD: {},
  YAMAARASHI: {},
  EXCALIBUR_BOX: {},
  FLAN: {},
  ELIOT: {},
  HARUKA: {},
  ARCANA: {},
  GALORE: {},
  RACHEL: {},
  TARA: {},
  SHIZURU: {},
  PRIMING: {},
  JULIAN: {},
  KAREN: {},
  JERBOA: {},
  SOLUM: {},
  BOX: {},
}
