const CHARACTER_DETAIL = {
  RAZIEL_THE_REMINISCE: {},
  SHIRE: {},
  PELOTA: {},
  DOROTHY: {},
  JOSHUA: {},
  SOMMER: {},
  USHANA: {},
  SUMMERSHIZURU: {},
  NICOLA: {},
  DUSTIN: {},
  ANFIYA: {},
  HAYABUSA: {},
  JALHAY: {},
  ITHOS: {},
  IKUMA: {},
  LISSANDRA: {},
  MUMEI: {},
  PALADI: {},
  CONNOR: {},
  VERLAINE: {},
  CHARLOTTE: {},
  SUEN: {},
  NAYUTA: {},
  KATAS: {},
  WENSHENG: {},
  MARGIELA: {},
  ARINA: {},
  ILONA: {},
  STELLA: {},
  CAROLINE: {
    SKILLS: [
      {
        amount: 2,
        cost: 3,
        name: '플라잉 플래시',
        desc: '[505] 1대를 보내 전장을 맴돌며 5초간 공격한 후 회수합니다. 지속시간 동안, 매초 적에게 1단 피해를 입히고 동시에 [인뢰]를 발동합니다. [505]는 [드론]입니다.',
      },
      {
        amount: 2,
        cost: 4,
        name: '자석 폭탄',
        desc: '자석폭탄 5개를 발사하여 범위 내의 적에게 5단 피해를 입히고 [자화]를 부여합니다. 동시에 [인뢰]를 발동합니다.',
      },
      {
        amount: 1,
        cost: 4,
        name: '번개 소용돌이',
        desc: '6초간 지속되는 번개 소용돌이를 시전합니다. 지속시간 동안, 아군의 모든 공격이 [인뢰]를 발동합니다. (피해형 특수 효과로 인한 명중 제외)',
      },
    ],
  },
  TENNIE: {},
  HEINRICH: {},
  LIVIA: {},
  DESIREE: {},
  LIN: {},
  NABI: {},
  GANYA: {},
  YEJUE: {},
  AKIRA: {},
  ACHIWA: {},
  KALEYA: {},
  YER: {},
  FENIA: {},
  RINA_F: {},
  VALENTINE: {},
  YOIDUKI: {},
  AOBA: {},
  CECIL: {},
  MHAR: {},
  MSGOLD: {},
  YAMAARASHI: {},
  EXCALIBUR_BOX: {},
  FLAN: {},
  ELIOT: {},
  HARUKA: {},
  ARCANA: {},
  GALORE: {},
  RACHEL: {},
  TARA: {},
  SHIZURU: {},
  PRIMING: {},
  JULIAN: {},
  KAREN: {},
  JERBOA: {},
  SOLUM: {},
  BOX: {},
}
