export enum CommentTarget {
  ResetMaraClearMind = 'reset-marathon-clear-mind',
  ResetMaraEquipment = 'reset-marathon-equipment',
  ResetMara002 = 'reset-marathon-002',
  TrainPower = 'train-power',
  TrainModulePowerSupply = 'train-module-power-supply',
  Archive = 'archive-',
  Character = 'character-',
  Equipment = 'equipment-',
  Material = 'material-',
  Monster = 'monster-',
  DeckDetail = 'deck-detail',
  EventCMChronicles = 'event-cheongmyeong-chronicles',
  EventBlackTeaWar = 'event-black-tea-war',
  EventStartDash = 'event-start-dash',
  EventSummerIsland = 'event-summer-island',
  Home = 'home',
  Free = 'free',
}
